
# Nombre de la aplicacion
spring.application.name=helpdesk-api

# configuracion de la base de datos 
spring.datasource.url=${URL_DB}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#Configuracion de Jpa/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop

jwt.secret=${JWT_SECRET}
jwt.expiration=900000
